### ISSUE TITLE
error while compling

### ISSUE THREAD

**Issue by NotteShock** [gianxddddd/ArchoMusicLinux#3]
i got this error while compiling please help i installed clang gcc and qt things but doesn't work i'm building this on my proot desktop [in](![Screenshot_2021-11-13_09-16-23](https://user-images.githubusercontent.com/85934291/141602249-54291bde-6e63-4bde-9f44-20b9ff1e0ea6.png)) my phone for arm devices please help gian

**Comment by NotteShock** [comment]
[
![Screenshot_2021-11-13_09-16-23](https://user-images.githubusercontent.com/85934291/141602275-83db4d40-7f14-47df-b887-850493b09abd.png)
](url)

**Comment by NotteShock** [comment]
i got this error please hels

**Comment by gianxddddd** [comment]
You should try migrating to Seren Music
